---
- name: boot settings
  become: true
  ansible.builtin.blockinfile:
    path: /boot/config.txt
    insertafter: '[all]'
    block: |
      gpu_mem=16
      force_turbo=1
      disable_splash=1
      boot_delay=1
      dtoverlay=pi3-disable-bt
