---
- name: cpu governor
  become: true
  ansible.builtin.blockinfile:
    path: /etc/rc.local
    insertbefore: 'exit 0'
    block: |
      echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
      echo performance > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
      echo performance > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
      echo performance > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
