---
# Rpi SDR Server deploy playbook


- name: prompt for required variables
  hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: target_host
      prompt: Enter the target rpi ip address
      default: "172.17.0.2"
      private: false
    - name: target_port
      prompt: Enter the target rpi ssh port
      default: "22"
      private: false
    - name: target_user
      prompt: Enter the target rpi ssh user
      default: "pi"
      private: false
    - name: target_passwd
      prompt: Enter the target rpi ssh password
      default: "raspberry"
      private: true
    - name: bot_token
      prompt: Enter telegram bot token
      private: false
    - name: bot_owner
      prompt: Enter telegram bot owner id
      private: false
    - name: bot_group
      prompt: Enter telegram bot group id
      private: false
  tasks:
    - name: save host value
      add_host:
        name: "{{ target_host }}"
        groups: rpisdr
    - name: save ssh values
      add_host:
        name: login
        port: "{{ target_port }}"
        username: "{{ target_user }}"
        password: "{{ target_passwd }}"
    - name: save bot values
      add_host:
        name: telegram
        token: "{{ bot_token }}"
        ownerid: "{{ bot_owner }}"
        groupid: "{{ bot_group }}"


- name: deploy rpi sdr server
  hosts: rpisdr
  vars:
    ansible_port: "{{ hostvars['login']['port'] }}"
    ansible_user: "{{ hostvars['login']['username'] }}"
    ansible_password: "{{ hostvars['login']['password'] }}"
    telegram_bot_token: "{{ hostvars['telegram']['token'] }}"
    telegram_bot_owner: "{{ hostvars['telegram']['ownerid'] }}"
    telegram_bot_group: "{{ hostvars['telegram']['groupid'] }}"
  roles:
    - basedeps
    - baseconfs
    - telegrambot
    - rtl-sdr
    - kalibrate
    - calibrate
    - spyserver
    - rtl433
    - airband
