---
- name: make scripts directory
  become: true
  ansible.builtin.file:
    path: /usr/local/src/scripts
    state: directory
    mode: 0755
    owner: root
    group: root

- name: copy custom calibrate script
  become: true
  ansible.builtin.copy:
    src: calibrate.sh
    dest: /usr/local/src/scripts/calibrate.sh
    mode: 0755
    owner: root
    group: root

- name: install custom calibrate script
  become: true
  ansible.builtin.file:
    src: /usr/local/src/scripts/calibrate.sh
    dest: /usr/local/bin/calibrate
    owner: root
    group: root
    mode: 0755
    state: link
